(in-package :oc)

#+NIL
(defmethod initialize-instance :after ((obj brep-builder-api-make-edge) &rest initargs
				&key L V1 V2 p1 p2 POINT1 POINT2 S &allow-other-keys)
  (let ((pointer
	 (cond ((and L S p2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_15 (ff-pointer L)
							    (ff-pointer S )
							    p1 p2))
	       ((and L p1 p2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_14 (ff-pointer L) p1 p2))
	       ((and (typep L 'geom-curve) V1 V2 p1 p2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_13 (ff-pointer L)
							    (ff-pointer V1)
							    (ff-pointer V2)
							    p1 p2))
	       ((and (typep L 'geom-curve) V1 V2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_12 (ff-pointer L)
							    (ff-pointer V1)
							    (ff-pointer V2)))
	       ((and (typep L 'gp:parab) V1 V2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_11 (ptr L)
							    (ff-pointer V1)
							    (ff-pointer V2)))
	       ((and (typep L 'gp:parab) POINT1 POINT2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_10 (ptr L)
							    (ptr POINT1) (ptr POINT2)))
	       ((and (typep L 'gp:parab) p1 p2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_9 (ptr L) p1 p2))
	       ((typep L 'gp:parab)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_8 (ptr L)))
	       ((and (typep L 'gp:circ) V1 V2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_7 (ptr L) (ff-pointer V1) (ff-pointer V2)))
	       ((and (typep L 'gp:circ) POINT1 POINT2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_6 (ptr L) (ptr POINT1) (ptr POINT2)))
	       ((and (typep L 'gp:circ) p1 p2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_5 (ptr L) p1 p2))
	       ((typep L 'gp:circ)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_4 (ptr L)))
	       ((and POINT1 POINT2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_3 (ptr POINT1) (ptr POINT2)))
	       ((and V1 V2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_2 (ff-pointer V1) (ff-pointer V2)))
	       (L (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_1 (ff-pointer L)))
	       ((and (null L) (null p1) (null p2)
		     (null V1) (null V2)
		     (null POINT1) (null POINT2)
		     (null S))
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_0))
	       (t (error "Invalid arguments to constructor: ~S" initargs)))))
    (setf (ff-pointer obj) pointer)
    (ff-pointer-finalize obj #'_wrap_delete_BRepBuilderAPI_MakeEdge)
    (values)))

(defmethod edge ((self brep-builder-api-make-edge))
  (let ((edge (allocate-instance (load-time-value (find-class 'topods-edge)))))
    (setf (ff-pointer edge) (_wrap_BrepBuilderAPI_MakeEdge_Edge (ff-pointer self)))
    edge))

#+NIL
(defmethod initialize-instance :after ((obj brep-builder-api-make-edge) &rest initargs
				       &key L S V1 V2 POINT1 POINT2 param1 param2 &allow-other-keys)
  (declare (ignore initargs))
  (setf (ff-pointer obj)
	(cond ((and (null L)
		    (null S)
		    (null V1)
		    (null V2)
		    (null POINT1)
		    (null POINT2)
		    (null param1)
		    (null param2)) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_0))
	      ((typep L 'geom2d-curve)
	       (cond ((and (typep S 'geom-surface) (typep param1 'double-float) (typep param2 'double-float))
		      (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_15 (ff-pointer L) (ff-pointer S) param1 param2))
		     (t (error "Invalid arguments to make-instance of BRepBuilderAPI_MakeEdge (1)."))))

	      ((typep L 'geom-curve)
	       (cond ((and (typep V1 'topods-vertex) (typep V2 'topods-vertex))
		      (cond ((and (typep param1 'double-float) (typep param2 'double-float))
			     (_wrap_new_BrepBuilderAPI_MakeEdge__SWIG_13
			      (ff-pointer L) (ff-pointer V1) (ff-pointer V2) param1 param2))
			    (t
			     (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_12
			      (ff-pointer L) (ff-pointer V1) (ff-pointer V2)))))
		     ((and (typep param1 'double-float) (typep param2 'double-float))
		      (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_14 (ff-pointer L) param1 param2))
		     (t (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_1 (ff-pointer L)))))

	      ((typep L 'gp:parab)
	       (cond ((and (typep V1 'topods-vertex) (typep V2 'topods-vertex))
		      (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_11 (ff-pointer L) (ff-pointer V1) (ff-pointer V2)))
		     ((and (typep POINT1 'gp:pnt) (typep POINT2 'gp:pnt))
		      (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_10
		       (ff-pointer L) (ff-pointer POINT1) (ff-pointer POINT2)))
		     ((and (typep param1 'double-float) (typep param2 'double-float))
		      (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_9 (ff-pointer L) param1 param2))
		     (t (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_8 (ff-pointer L)))))
	 
	      ((typep L 'gp:circ)
	       (cond ((and (typep V1 'topods-vertex) (typep V2 'topods-vertex))
		      (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_7 (ff-pointer L) (ff-pointer V1) (ff-pointer V2)))
		     ((and (typep POINT1 'gp:pnt) (typep POINT2 'gp:pnt))
		      (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_6 (ff-pointer L) (ff-pointer POINT1) (ff-pointer POINT2)))
		     ((and (typep param1 'double-float) (typep param2 'double-float))
		      (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_5 (ff-pointer L) param1 param2))
		     (t (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_4 (ff-pointer L)))))
	 
	      ((and (typep POINT1 'gp:pnt) (typep POINT2 'gp:pnt))
	       (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_3 (ff-pointer POINT1) (ff-pointer POINT2)))
	
	      ((and (typep V1 'topods-vertex) (typep V2 'topods-vertex))
	       (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_2 (ff-pointer V1) (ff-pointer V2)))
  
	      (t (error "Invalid arguments to make-instance of BRepBuilderAPI_MakeEdge (2)."))))
  (ff-pointer-finalize obj #'_wrap_delete_BRepBuilderAPI_MakeEdge)
	       (values))


(defmethod initialize-instance :after ((obj brep-builder-api-make-edge) &rest initargs
				       &key L S V1 V2 Pnt1 Pnt2 param1 param2 &allow-other-keys)
  (let ((pointer
	 (cond ((and L S V1 V2 param1 param2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_33 (ff-pointer L) (ff-pointer S) (ff-pointer V1) (ff-pointer V2) (coerce param1 'double-float) (coerce param2 'double-float)))
	       ((and L S Pnt1 Pnt2 param1 param2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_32 (ff-pointer L) (ff-pointer S) (ptr Pnt1) (ptr Pnt2) (coerce param1 'double-float) (coerce param2 'double-float)))
	       ((and L S V1 V2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_31 (ff-pointer L) (ff-pointer S) (ff-pointer V1) (ff-pointer V2)))
	       ((and L S param1 param2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_30 (ff-pointer L) (ff-pointer S) (coerce param1 'double-float) (coerce param2 'double-float)))
	       ((and L S)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_29 (ff-pointer L) (ff-pointer S)))
	       ((and L V1 V2 param1 param2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_28 (ff-pointer L) (ff-pointer V1) (ff-pointer V2) (coerce param1 'double-float) (coerce param2 'double-float)))
	       ((and L Pnt1 Pnt2 param1 param2)
		(typecase L
		  (geom2d-curve (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_27 (ff-pointer L) (ptr Pnt1) (ptr Pnt2) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (t (error "Invalid arguments to make-instance of BRepBuilderAPI_MakeEdge (1): ~S." initargs))))
	       ((and L V1 V2)
		(typecase L
		  (geom-curve (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_26 (ff-pointer L) (ff-pointer V1) (ff-pointer V2)))
		  (gp:parab (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_22 (ptr L) (ff-pointer V1) (ff-pointer V2)))
		  (gp:hypr (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_18 (ptr L) (ff-pointer V1) (ff-pointer V2)))
		  (gp:elips (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_14 (ptr L) (ff-pointer V1) (ff-pointer V2)))
		  (gp:circ (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_10 (ptr L) (ff-pointer V1) (ff-pointer V2)))
		  (gp:lin (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_6 (ptr L) (ff-pointer V1) (ff-pointer V2)))
		  (t (error "Invalid arguments to make-instance of BRepBuilderAPI_MakeEdge (2): ~S." initargs))))			    
	       ((and L Pnt1 Pnt2)
		(typecase L
		  (geom-curve (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_25 (ff-pointer L) (ptr Pnt1) (ptr Pnt2)))
		  (gp:parab (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_21 (ptr L) (ptr Pnt1) (ptr Pnt2)))
		  (gp:hypr (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_17 (ptr L) (ptr Pnt1) (ptr Pnt2)))
		  (gp:elips (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_13 (ptr L) (ptr Pnt1) (ptr Pnt2)))
		  (gp:circ (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_9 (ptr L) (ptr Pnt1) (ptr Pnt2)))
		  (gp:lin (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_5 (ptr L) (ptr Pnt1) (ptr Pnt2)))
		  (t (error "Invalid arguments to make-instance of BRepBuilderAPI_MakeEdge (3): ~S." initargs))))
	       ((and L param1 param2)
		(typecase L
		  (geom-curve (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_24 (ff-pointer L) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (gp:parab (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_20 (ptr L) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (gp:hypr (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_16 (ptr L) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (gp:elips (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_12 (ptr L) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (gp:circ (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_8 (ptr L) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (gp:lin (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_4 (ptr L) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (t (error "Invalid arguments to make-instance of BRepBuilderAPI_MakeEdge (4): ~S." initargs))))
	       ((typep L 'geom-curve) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_23 (ff-pointer L)))
	       ((typep L 'gp:parab) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_19 (ptr L)))
	       ((typep L 'gp:hypr) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_15 (ptr L)))
	       ((typep L 'gp:elips) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_11 (ptr L)))
	       ((typep L 'gp:circ) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_7 (ptr L)))
	       ((typep L 'gp:lin) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_3 (ptr L)))
	       ((and V1 V2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_1 (ff-pointer V1) (ff-pointer V2)))
	       ((and Pnt1 Pnt2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_2 (ptr Pnt1) (ptr Pnt2)))
	       ((null (or L S V1 V2 param1 param2))
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_0))
	       (t (error "Invalid arguments to make-instance of BRepBuilderAPI_MakeEdge (5): ~S." initargs)))))
    (setf (ff-pointer obj) pointer)
    (ff-pointer-finalize obj #'_wrap_delete_BRepBuilderAPI_MakeEdge)
    (values)))
