(in-package :oc)

(defmethod edge ((self brep-builder-api-make-edge))
  (let ((edge (allocate-instance (load-time-value (find-class 'topods-edge)))))
    (setf (ff-pointer edge) (_wrap_TopoDS_Shape_copy_reference
			     (_wrap_BrepBuilderAPI_MakeEdge_Edge (ff-pointer self))))
    edge))

(defmethod initialize-instance :after ((obj brep-builder-api-make-edge) &rest initargs
				       &key L S V1 V2 Pnt1 Pnt2 param1 param2 &allow-other-keys)
  (let ((pointer
	 (cond ((and L S V1 V2 param1 param2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_33 (ff-pointer L) (ff-pointer S) (ff-pointer V1) (ff-pointer V2) (coerce param1 'double-float) (coerce param2 'double-float)))
	       ((and L S Pnt1 Pnt2 param1 param2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_32 (ff-pointer L) (ff-pointer S) (ptr Pnt1) (ptr Pnt2) (coerce param1 'double-float) (coerce param2 'double-float)))
	       ((and L S V1 V2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_31 (ff-pointer L) (ff-pointer S) (ff-pointer V1) (ff-pointer V2)))
	       ((and L S param1 param2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_30 (ff-pointer L) (ff-pointer S) (coerce param1 'double-float) (coerce param2 'double-float)))
	       ((and L S)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_29 (ff-pointer L) (ff-pointer S)))
	       ((and L V1 V2 param1 param2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_28 (ff-pointer L) (ff-pointer V1) (ff-pointer V2) (coerce param1 'double-float) (coerce param2 'double-float)))
	       ((and L Pnt1 Pnt2 param1 param2)
		(typecase L
		  (geom2d-curve (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_27 (ff-pointer L) (ptr Pnt1) (ptr Pnt2) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (t (error "Invalid arguments to make-instance of BRepBuilderAPI_MakeEdge (1): ~S." initargs))))
	       ((and L V1 V2)
		(typecase L
		  (geom-curve (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_26 (ff-pointer L) (ff-pointer V1) (ff-pointer V2)))
		  (gp:parab (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_22 (ptr L) (ff-pointer V1) (ff-pointer V2)))
		  (gp:hypr (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_18 (ptr L) (ff-pointer V1) (ff-pointer V2)))
		  (gp:elips (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_14 (ptr L) (ff-pointer V1) (ff-pointer V2)))
		  (gp:circ (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_10 (ptr L) (ff-pointer V1) (ff-pointer V2)))
		  (gp:lin (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_6 (ptr L) (ff-pointer V1) (ff-pointer V2)))
		  (t (error "Invalid arguments to make-instance of BRepBuilderAPI_MakeEdge (2): ~S." initargs))))			    
	       ((and L Pnt1 Pnt2)
		(typecase L
		  (geom-curve (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_25 (ff-pointer L) (ptr Pnt1) (ptr Pnt2)))
		  (gp:parab (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_21 (ptr L) (ptr Pnt1) (ptr Pnt2)))
		  (gp:hypr (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_17 (ptr L) (ptr Pnt1) (ptr Pnt2)))
		  (gp:elips (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_13 (ptr L) (ptr Pnt1) (ptr Pnt2)))
		  (gp:circ (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_9 (ptr L) (ptr Pnt1) (ptr Pnt2)))
		  (gp:lin (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_5 (ptr L) (ptr Pnt1) (ptr Pnt2)))
		  (t (error "Invalid arguments to make-instance of BRepBuilderAPI_MakeEdge (3): ~S." initargs))))
	       ((and L param1 param2)
		(typecase L
		  (geom-curve (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_24 (ff-pointer L) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (gp:parab (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_20 (ptr L) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (gp:hypr (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_16 (ptr L) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (gp:elips (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_12 (ptr L) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (gp:circ (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_8 (ptr L) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (gp:lin (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_4 (ptr L) (coerce param1 'double-float) (coerce param2 'double-float)))
		  (t (error "Invalid arguments to make-instance of BRepBuilderAPI_MakeEdge (4): ~S." initargs))))
	       ((typep L 'geom-curve) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_23 (ff-pointer L)))
	       ((typep L 'gp:parab) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_19 (ptr L)))
	       ((typep L 'gp:hypr) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_15 (ptr L)))
	       ((typep L 'gp:elips) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_11 (ptr L)))
	       ((typep L 'gp:circ) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_7 (ptr L)))
	       ((typep L 'gp:lin) (_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_3 (ptr L)))
	       ((and V1 V2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_1 (ff-pointer V1) (ff-pointer V2)))
	       ((and Pnt1 Pnt2)
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_2 (ptr Pnt1) (ptr Pnt2)))
	       ((null (or L S V1 V2 param1 param2))
		(_wrap_new_BRepBuilderAPI_MakeEdge__SWIG_0))
	       (t (error "Invalid arguments to make-instance of BRepBuilderAPI_MakeEdge (5): ~S." initargs)))))
    (setf (ff-pointer obj) pointer)
    (oc:finalize obj)
    (values)))
