(in-package :gp)

(defun oc::ax2 (&key (P (pnt 0.0d0 0.0d0 0.0d0)) (Vx (dir 1.0d0 0.0d0 0.0d0)))
  (let* ((pointer (oc::_wrap_new_gp_Ax2__SWIG_2 (ptr P) (ptr Vx)))
	 (struct (gp:make-ax2 :ptr pointer)))
    (oc:finalize struct)
    struct))

(defun ax2 (&key (P (pnt 0.0d0 0.0d0 0.0d0)) (N (dir 0.0d0 0.0d0 1.0d0)) (Vx (dir 1.0d0 0.0d0 0.0d0)))
  (let* ((pointer (foreign-alloc '(:struct gp-ax2)))
	 (struct (make-ax2 :ptr pointer)))
    (setf (gp-ax2-axis-loc-coord-x pointer) (x P)
	  (gp-ax2-axis-loc-coord-y pointer) (y P)
	  (gp-ax2-axis-loc-coord-z pointer) (z P)
	  (gp-ax2-axis-vdir-coord-x pointer) (x N)
	  (gp-ax2-axis-vdir-coord-y pointer) (y N)
	  (gp-ax2-axis-vdir-coord-z pointer) (z N)
	  (gp-ax2-vxdir-coord-x pointer) (- (* (y N) (- (* (x Vx) (y N)) (* (y Vx) (x N))))
					    (* (z N) (- (* (z Vx) (x N)) (* (x Vx) (z N)))))
	  (gp-ax2-vxdir-coord-y pointer) (- (* (z N) (- (* (y Vx) (z N)) (* (z Vx) (y N))))
					    (* (x N) (- (* (x Vx) (y N)) (* (y Vx) (x N)))))
	  (gp-ax2-vxdir-coord-z pointer) (- (* (x N) (- (* (z Vx) (x N)) (* (x Vx) (z N))))
					    (* (y N) (- (* (y Vx) (z N)) (* (z Vx) (y N)))))
	  (gp-ax2-vydir-coord-x pointer) (- (* (y N) (gp-ax2-vxdir-coord-z pointer))
					    (* (z N) (gp-ax2-vxdir-coord-y pointer)))
	  (gp-ax2-vydir-coord-y pointer) (- (* (z N) (gp-ax2-vxdir-coord-x pointer))
					    (* (x N) (gp-ax2-vxdir-coord-z pointer)))
	  (gp-ax2-vydir-coord-z pointer) (- (* (x N) (gp-ax2-vxdir-coord-y pointer))
					    (* (y N) (gp-ax2-vxdir-coord-x pointer))))
    (oc:finalize struct :native)
    struct))

(defmethod print-object ((object ax2) stream)
  (let ((pointer (ptr object)))
    (format stream "(ax2 :P (pnt ~A ~A ~A) :N (dir ~A ~A ~A) :Vx (dir ~A ~A ~A))"
	    (gp-ax2-axis-loc-coord-x pointer)
	    (gp-ax2-axis-loc-coord-y pointer)
	    (gp-ax2-axis-loc-coord-z pointer)
	    
	    (gp-ax2-axis-vdir-coord-x pointer)
	    (gp-ax2-axis-vdir-coord-y pointer)
	    (gp-ax2-axis-vdir-coord-z pointer)
	    
	    (gp-ax2-vxdir-coord-x pointer)
	    (gp-ax2-vxdir-coord-y pointer)
	    (gp-ax2-vxdir-coord-z pointer))))
