(in-package :oc)

(defmethod initialize-instance :after ((object brep-offset-api-make-thick-solid) &rest initargs
				       &key S ClosingFaces Offset Tol Mode Intersection
					 SelfInter Join RemoveIntEdges &allow-other-keys)
  (let ((pointer
	 (cond ((and S ClosingFaces Offset Tol Mode Intersection SelfInter Join RemoveIntEdges)
		(_wrap_new_BrepOffsetAPI_MakeThickSolid__SWIG_1 (ff-pointer S) (ff-pointer ClosingFaces)
								(coerce Offset 'double-float) (coerce Tol 'double-float)
								Mode (if Intersection (if (eq Intersection 0) 0 1) 0)
								(if SelfInter (if (eq SelfInter 0) 0 1) 0) Join
								(if RemoveIntEdges (if (eq RemoveIntEdges 0) 0 1) 0)))
	       ((and S ClosingFaces Offset Tol Mode Intersection SelfInter Join)
		(_wrap_new_BrepOffsetAPI_MakeThickSolid__SWIG_2 (ff-pointer S) (ff-pointer ClosingFaces)
								(coerce Offset 'double-float) (coerce Tol 'double-float)
								Mode (if Intersection (if (eq Intersection 0) 0 1) 0)
								(if SelfInter (if (eq SelfInter 0) 0 1) 0) Join))
	       ((and S ClosingFaces Offset Tol Mode Intersection SelfInter)
		(_wrap_new_BrepOffsetAPI_MakeThickSolid__SWIG_3 (ff-pointer S) (ff-pointer ClosingFaces)
								(coerce Offset 'double-float) (coerce Tol 'double-float)
								Mode (if Intersection (if (eq Intersection 0) 0 1) 0)
								(if SelfInter (if (eq SelfInter 0) 0 1) 0)))
	       ((and S ClosingFaces Offset Tol Mode Intersection)
		(_wrap_new_BrepOffsetAPI_MakeThickSolid__SWIG_4 (ff-pointer S) (ff-pointer ClosingFaces)
								(coerce Offset 'double-float) (coerce Tol 'double-float)
								Mode (if Intersection (if (eq Intersection 0) 0 1) 0)))
	       ((and S ClosingFaces Offset Tol Mode)
		(_wrap_new_BrepOffsetAPI_MakeThickSolid__SWIG_5 (ff-pointer S) (ff-pointer ClosingFaces)
								(coerce Offset 'double-float) (coerce Tol 'double-float)
								Mode))
	       ((and S ClosingFaces Offset Tol)
		(_wrap_new_BrepOffsetAPI_MakeThickSolid__SWIG_6 (ff-pointer S) (ff-pointer ClosingFaces)
								(coerce Offset 'double-float) (coerce Tol 'double-float)))
	       ((null (or S ClosingFaces Offset Tol Mode Intersection SelfInter Join RemoveIntEdges))
		(_wrap_new_BRepOffsetAPI_MakeThickSolid__SWIG_0))
	       (t (error "Invalid arguments to constructor ~S" initargs)))))
    (setf (ff-pointer object) pointer)
    (values)))
